config/routes.rb
Rails.application.routes.draw do
  get 'artists/index'
  get 'artists/new'
  root 'billboards#index'

  resources :billboards
  resources :songs do
    resources :artists, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard
  belongs_to :song
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    has_many :artists, dependent: :destroy
    has_many :songs, through: :artists
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :artists, dependent: :destroy
    has_many :billboards, through: :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_song
  
  def index
    @artists = Artist.all
  end

  def new
    @artists = Artist.all - @song.billboards
    @artist = @song.artists.new
  end

  def create
    @artist = @song.artists.new(artist_params)
    if @artist.save
      redirect_to song_artists_path(@song)
    else
      render :new
    end
  end

  def destroy
    @artist = @song.artists.find(params[:id])
    @artist.destroy
    redirect_to song_artists_path(@song)
  end

  private
  def set_song
    @song = Song.find(params[:song_id])
  end 

  def artist_params
    params.require(:artists).permit(:billboard_id)
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :destroy]
  
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to @billboard
    else
      render :new
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
  def set_billboard
    @billboard = Billboard.find(params[:id])
  end 

  def billboard_params
    params.require(:billboard).permit(:title)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :destroy]
  
  def index
    @song = Song.all
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.create(song_params)
    
    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1><%= @song.title %>: Artists</h1>
<%= link_to 'Add Artist', new_song_artist_path(@song) %>
<hr/>

<h2>Artist</h2>
<ul>
    <% @artists.each do |artist| %>
        <li>
            <%= artist.billboard.title %>
            <br/>
            <%= link_to 'Remove', song_artist_path(@song, artist), method: :delete %>
        </li>
    <% end %>
</ul>

app/views/artists/new.html.erb
<h1>Add Artist</h1>
<%= form_with(model: [@song, @artist], local: true, class: "ui form" ) do |f| %>
    <%= f.label :billboard %>
    <%# f.select :billboard_id, @billboards.collect { |u| [u.title, u.id] } %>
    <br/>
    <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/billboards/index.html.erb
<h1>Billboards</h1>
<%= link_to 'Add Billboard', new_billboard_path %>
<hr/>
<ul>
    <% @billboards.each do |billboard| %>
        <li>
            <%= link_to billboard.title, billboard %>
        </li>
    <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Add Billboard</h1>
<%= form_with(model: @billboard, local: true, class: "ui form" ) do |f| %>
    <div class = "field">
        <%= f.label :title %>
        <%= f.text_field :title, required: true, autofocus: true, placeholder: "Billboard Title" %>
    </div>
    <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/billboards/show.html.erb
<h1><%= @billboard.title %></h1>
<hr/>
<h2>Songs</h2>
<ul>
    <% @billboard.songs.each do |song| %>
        <li>
            <%= link_to song.title, song %>
        </li>
    <% end %>
</ul>
<br/>
<br/>
<br/>
<%= link_to 'Delete Billboard', @billboard, method: :delete, class: "ui red button inverted" %>

app/views/layouts/_navbar.html.erb
<nav>
    <ul>
        <li>
            <%= link_to 'Songs', songs_path %>
        </li>
        <li>
            <%= link_to 'Add Songs', new_song_path %>
        </li>
        <li>
            <%= link_to 'Billboards', billboards_path %>
        </li>
        <li>
            <%= link_to 'Add Billboard', new_billboard_path %>
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotifyTop100</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class = "ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/index.html.erb
<h1>Songs</h1>
<%= link_to 'Add Song', new_song_path %>
<hr/>

<ul>
    <% @songs.each do |song| %>
        <li>
            <%= link_to song.title, song %>
        </li>
    <% end %>
</ul>

app/views/songs/new.html.erb
<h1>Add Song</h1>
<%= form_with(model: @song, local: true, class: "ui form" ) do |f| %>
    <div class = "field">
        <%= f.label :title %>
        <%= f.text_field :title, required: true, placeholder: "Song Title" %>
    </div>
    <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<hr/>
<br/>
<%= link_to 'Artists', song_artists_path(@song), class: "ui primary button inverted" %>
<br/>
<br/>
<br/>
<%= link_to "Delete Song", @song, method: :delete, class: "ui red button inverted" %>